// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item/item.proto

/*
Package item is a generated protocol buffer package.

It is generated from these files:
	item/item.proto

It has these top-level messages:
	Item
	GetItemRequest
	ListItemsRequest
	ListItemsResponse
*/
package item

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetItemRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetItemRequest) Reset()                    { *m = GetItemRequest{} }
func (m *GetItemRequest) String() string            { return proto.CompactTextString(m) }
func (*GetItemRequest) ProtoMessage()               {}
func (*GetItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListItemsRequest struct {
}

func (m *ListItemsRequest) Reset()                    { *m = ListItemsRequest{} }
func (m *ListItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListItemsRequest) ProtoMessage()               {}
func (*ListItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListItemsResponse struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ListItemsResponse) Reset()                    { *m = ListItemsResponse{} }
func (m *ListItemsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListItemsResponse) ProtoMessage()               {}
func (*ListItemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "item.Item")
	proto.RegisterType((*GetItemRequest)(nil), "item.GetItemRequest")
	proto.RegisterType((*ListItemsRequest)(nil), "item.ListItemsRequest")
	proto.RegisterType((*ListItemsResponse)(nil), "item.ListItemsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ItemService service

type ItemServiceClient interface {
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*Item, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := grpc.Invoke(ctx, "/item.ItemService/GetItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	out := new(ListItemsResponse)
	err := grpc.Invoke(ctx, "/item.ItemService/ListItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ItemService service

type ItemServiceServer interface {
	GetItem(context.Context, *GetItemRequest) (*Item, error)
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/ListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _ItemService_GetItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _ItemService_ListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item/item.proto",
}

func init() { proto.RegisterFile("item/item.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x6b, 0x83, 0x40,
	0x14, 0xc4, 0xf1, 0x4f, 0x5b, 0x7c, 0x82, 0x6d, 0x1f, 0xa5, 0x5d, 0x3c, 0x2d, 0x7b, 0x12, 0x0a,
	0x16, 0x2c, 0xbd, 0xf5, 0x1e, 0x02, 0x9e, 0xcc, 0x27, 0x48, 0xf4, 0x1d, 0xf6, 0xa0, 0x6b, 0xdc,
	0x4d, 0xc8, 0xc7, 0x0f, 0xbb, 0x2b, 0xc1, 0x98, 0x8b, 0x3c, 0x67, 0x86, 0x99, 0x1f, 0x0b, 0xaf,
	0xd2, 0x50, 0xff, 0x63, 0x3f, 0xe5, 0x38, 0x29, 0xa3, 0x30, 0xb6, 0xb7, 0xa8, 0x21, 0xde, 0x1a,
	0xea, 0x31, 0x83, 0x50, 0x76, 0x2c, 0xe0, 0x41, 0x91, 0x34, 0xa1, 0xec, 0x10, 0x21, 0x1e, 0xf6,
	0x3d, 0xb1, 0xd0, 0x29, 0xee, 0x46, 0x0e, 0x69, 0x47, 0xba, 0x9d, 0xe4, 0x68, 0xa4, 0x1a, 0x58,
	0xe4, 0xac, 0xa5, 0x24, 0x38, 0x64, 0x1b, 0x32, 0xb6, 0xb0, 0xa1, 0xe3, 0x89, 0xb4, 0x59, 0xf7,
	0x0a, 0x84, 0xb7, 0x5a, 0x6a, 0x17, 0xd1, 0x73, 0x46, 0xfc, 0xc1, 0xfb, 0x42, 0xd3, 0xa3, 0x1a,
	0xb4, 0x1d, 0x7b, 0xb2, 0x80, 0x9a, 0x05, 0x3c, 0x2a, 0xd2, 0x0a, 0x4a, 0x87, 0xee, 0xaa, 0xbd,
	0x51, 0x5d, 0x20, 0xb5, 0xbf, 0x3b, 0x9a, 0xce, 0xb2, 0x25, 0xfc, 0x86, 0x97, 0x79, 0x1b, 0x3f,
	0x7c, 0xf8, 0x1e, 0x25, 0x5f, 0x54, 0xe0, 0x3f, 0x24, 0xb7, 0x49, 0xfc, 0xf4, 0xc6, 0x9a, 0x2b,
	0xff, 0x7a, 0xd0, 0x3d, 0xdb, 0xe1, 0xd9, 0xbd, 0xe0, 0xef, 0x35, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0xe6, 0x34, 0xc8, 0x54, 0x01, 0x00, 0x00,
}
