// Code generated by protoc-gen-gogo.
// source: order/order.proto
// DO NOT EDIT!

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	order/order.proto

It has these top-level messages:
	Order
	CreateOrderRequest
	GetOrderRequest
	GetOrderDetailRequest
	GetOrderDetailResponse
	ListOrdersRequest
	ListOrdersResponse
	DeleteOrderRequest
*/
package order

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/bakins/kubernetes-envoy-example/api/item"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Order) Validate() error {
	return nil
}
func (this *CreateOrderRequest) Validate() error {
	return nil
}
func (this *GetOrderRequest) Validate() error {
	return nil
}
func (this *GetOrderDetailRequest) Validate() error {
	return nil
}
func (this *GetOrderDetailResponse) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
func (this *ListOrdersRequest) Validate() error {
	return nil
}
func (this *ListOrdersResponse) Validate() error {
	for _, item := range this.Orders {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Orders", err)
			}
		}
	}
	return nil
}
func (this *DeleteOrderRequest) Validate() error {
	return nil
}
