<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/item/item.proto

namespace Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>item.ListItemsRequest</code>
 */
class ListItemsRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Proto\Item\Item::initOnce();
        parent::__construct();
    }

}

