<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/item/item.proto

namespace Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>item.ListItemsResponse</code>
 */
class ListItemsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .item.Item items = 1;</code>
     */
    private $items;

    public function __construct() {
        \GPBMetadata\Proto\Item\Item::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .item.Item items = 1;</code>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * <code>repeated .item.Item items = 1;</code>
     */
    public function setItems(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Item\Item::class);
        $this->items = $arr;
    }

}

