#!/bin/bash
set -ex

eval $(minikube docker-env --shell bash)

pushd ./item
#docker build -t quay.io/bakins/kubernetes-envoy-example-php:latest .
popd

#exit

for CMD in frontend; do
    docker run -t \
        -v `pwd`:/go/src/github.com/bakins/kubernetes-envoy-example \
        -w /go/src/github.com/bakins/kubernetes-envoy-example\
        golang:1.9-alpine \
        sh -c "go build -o bin/$CMD ./cmd/$CMD"
done

docker build -t quay.io/bakins/kubernetes-envoy-example:latest .
