<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/item/item.proto

namespace GPBMetadata\Proto\Item;

class Item
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8020a1570726f746f2f6974656d2f6974656d2e70726f746f12046974" .
            "656d22350a044974656d120a0a026964180120012809120c0a046e616d65" .
            "18022001280912130a0b6465736372697074696f6e180320012809221c0a" .
            "0e4765744974656d52657175657374120a0a02696418012001280922120a" .
            "104c6973744974656d7352657175657374222e0a114c6973744974656d73" .
            "526573706f6e736512190a056974656d7318012003280b320a2e6974656d" .
            "2e4974656d32780a0b4974656d53657276696365122b0a07476574497465" .
            "6d12142e6974656d2e4765744974656d526571756573741a0a2e6974656d" .
            "2e4974656d123c0a094c6973744974656d7312162e6974656d2e4c697374" .
            "4974656d73526571756573741a172e6974656d2e4c6973744974656d7352" .
            "6573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

